# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: MaRu - AI×Web Design Creative Studio
email: tkmr.3aeau@gmail.com
description: >-
  AIにのめり込む30代。テクノロジーとクリエイティビティの融合を追求し、最新のAI技術を活用したWebデザインやコンテンツ制作を手がけています。日々進化するデジタル世界で、人とテクノロジーをつなぐ架け橋となることを目指しています。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maru-vive.com" # the base hostname & protocol for your site, e.g. http://example.com
version: "2.0.0"
twitter_username: Maru44448476
github_username:  your_github_username

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
  works:
    output: true
    permalink: /works/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      lang: "ja"

# Pagination
paginate: 6
paginate_path: "/works/page:num/"

# SEO
lang: ja
author: MaRu
social:
  name: MaRu
  links:
    - https://x.com/Maru44448476
    - https://note.com/maru4444

# Analytics
google_analytics: G-NZRXQQ8WSZ

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/