version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.3.2
    container_name: maru-portfolio-jekyll
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --livereload --watch --force_polling
      "
    stdin_open: true
    tty: true

volumes:
  bundle_cache: